"""Makes Velora's Android launcher icons from the app logo.

    python scripts/generate_launcher_icons.py

Writes the classic icon for older launchers, and an adaptive icon (logo in
front, a warm cream behind) that each launcher trims to its own shape.
Run it again after changing assets/images/logo/Velora_app_logo.png.
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
LOGO = ROOT / 'assets/images/logo/Velora_app_logo.png'
RES = ROOT / 'android/app/src/main/res'

# Shows through the logo's rounded corners on square-ish launcher shapes.
BACKGROUND = '#FDF1E4'

DENSITIES = {'mdpi': 1, 'hdpi': 1.5, 'xhdpi': 2, 'xxhdpi': 3, 'xxxhdpi': 4}

# An adaptive icon is a 108dp layer and launchers show about the middle
# 72dp. Drawing the logo at 80dp fills that window, so round masks show
# only artwork, and trim just the logo's outer 4dp.
LAYER_DP = 108
LOGO_DP = 80


def main() -> None:
    logo = Image.open(LOGO).convert('RGBA')

    for name, scale in DENSITIES.items():
        folder = RES / f'mipmap-{name}'
        folder.mkdir(exist_ok=True)

        # Classic icon: the logo as drawn, 48dp.
        size = round(48 * scale)
        logo.resize((size, size), Image.LANCZOS).save(
            folder / 'ic_launcher.png', optimize=True
        )

        # Adaptive foreground: the logo centred on a transparent layer.
        layer = round(LAYER_DP * scale)
        inner = round(LOGO_DP * scale)
        canvas = Image.new('RGBA', (layer, layer), (0, 0, 0, 0))
        offset = (layer - inner) // 2
        canvas.alpha_composite(
            logo.resize((inner, inner), Image.LANCZOS), (offset, offset)
        )
        canvas.save(folder / 'ic_launcher_foreground.png', optimize=True)

    anydpi = RES / 'mipmap-anydpi-v26'
    anydpi.mkdir(exist_ok=True)
    (anydpi / 'ic_launcher.xml').write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by scripts/generate_launcher_icons.py -->\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/ic_launcher_background" />\n'
        '    <foreground android:drawable="@mipmap/ic_launcher_foreground" />\n'
        '</adaptive-icon>\n',
        encoding='utf-8',
    )
    (RES / 'values/ic_launcher_colors.xml').write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by scripts/generate_launcher_icons.py -->\n'
        '<resources>\n'
        f'    <color name="ic_launcher_background">{BACKGROUND}</color>\n'
        '</resources>\n',
        encoding='utf-8',
    )
    print('Launcher icons written.')


if __name__ == '__main__':
    main()
